profile: basic
classify:
  filesystem_read:
  - fd
  - mmdc
  - jq
  - man
  - ls
  - head
  - grep
  - tail
  lang_exec:
  - tmux
  - bazel
  - gopls
  package_run:
  - mise
  - goenv
  - bazel test
  git_write:
  - git worktree
  git_safe:
  - mcp__github__search_pull_requests
  - mcp__github__pull_request_read
  db_read:
  - mcp__jira__getJiraIssue
  - mcp__jira__getConfluencePage
  filesystem_write:
  - pnpm fmt:write:path
actions:
  lang_exec: allow
  /Users/db/db/bin/hh: allow
  grep: allow
  pnpm oxlint:js: allow
  pnpm ts: allow
  pnpm build: allow
  pnpm *: allow
  pnpm test:base: allow
  pnpm test: allow
  mcp__datadog__analyze_datadog_logs: allow
  mcp__datadog__search_datadog_logs: allow
  pnpm vitest run: allow
