notARepository: 'skip'

os:
  editPreset: 'nvim'

keybinding:
  universal:
    openRecentRepos: '`'

gui:
 # Catppuccin Mocha
 theme:
   activeBorderColor:
     - '#a6e3a1'
     - bold
   inactiveBorderColor:
     - '#6c7086'
   optionsTextColor:
     - '#89b4fa'
   selectedLineBgColor:
     - '#252530'
   selectedRangeBgColor:
     - '#252530'
   cherryPickedCommitBgColor:
     - '#45475a'
   cherryPickedCommitFgColor:
     - '#a6e3a1'
   unstagedChangesColor:
     - '#f38ba8'
   defaultFgColor:
     - '#e8ecfa'
   searchingActiveBorderColor:
     - '#f9e2af'

