customCommands:
  - key: '|'
    context: 'global'
    prompts:
      - type: 'input'
        title: 'What changes are you working on?'
        key: 'CommitMessage'
        initialValue: ''
    command: 'r=$(git rev-parse --show-toplevel) && f="${r}/.gitpre" && echo "Last message:" && tail ${f} && echo "{{.Form.CommitMessage}}" > ${f}'
    loadingText: 'Saving message in .gitpre'
    stream: true
