os:
  editPreset: 'nvim'

gui:
 # Modified mocha catppuccin theme
 theme:
   activeBorderColor:
     - '#bd93f9'
     - bold
   inactiveBorderColor:
     - '#a6adc8'
   optionsTextColor:
     - '#89b4fa'
   selectedLineBgColor:
     - '#393a4f'
   selectedRangeBgColor:
     - '#393a4f'
   cherryPickedCommitBgColor:
     - '#45475a'
   cherryPickedCommitFgColor:
     - '#89b4fa'
   unstagedChangesColor:
     - '#FF79C6'
   defaultFgColor:
     - '#cdd6f4'
   searchingActiveBorderColor:
     - '#f9e2af'

