-- [[ Neovim Configuration ]]
require('config.options')
require('config.keymaps')
require('config.autocmds')
require('config.lazy-plugins')
require('config.lsp')
require('config.completion')
require('config.telescope')
require('config.treesitter')
require('config.ui')
